version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: rdjava_postgres_container
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '1234'
      POSTGRES_DB: 'postgres'
    networks:
      - db-network
    volumes:
      - ../src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest